services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=flask
      - POSTGRES_DB=todo_list
    ports:
      - 5432:5432
  web:
    build:
      context: .
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=flask
      - POSTGRES_DB=todo_list
      - POSTGRES_HOST=db
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/app
