services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=flask
      - POSTGRES_DB=todo_list
    ports:
      - 5432:5432
  todoservice:
    build:
      context: ./todoservice
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=flask
      - POSTGRES_DB=todo_list
      - POSTGRES_HOST=db
    volumes:
      - ./todoservice:/app
    ports:
      - 8002:80
  notificationservice:
    build:
      context: ./notificationservice
    volumes:
      - ./notificationservice:/app
  kafka:
    image: "bitnami/kafka:latest"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
