apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-starter
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: flask-starter
          image: rohit20001221/flask-starter:latest
          ports:
            - containerPort: 80
