---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-starter
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-starter
          image: rohit20001221/flask-starter:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flask-starter
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---

